package com.mipo256.podlodka.patterns.evaluatoroptimizer;

import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.SystemMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.ai.converter.BeanOutputConverter;

public class EvaluatorOptimizerService {

    private static final Logger log = LoggerFactory.getLogger(EvaluatorOptimizerService.class);

    private final PromptTemplate USER_PROMPT_EVALUATOR_TEMPLATE = new PromptTemplate("""
            Please, generate the source code in Java programming language that solves the outlined problem.
            
            Consider everything that might be important:
            
            - Thread safety
            - Cyclomatic Complexity of code
            - Optimal performance of the generated code
            - Extensibility and Maintainability of the code etc.
            
            Here is the task:
            
            {content}

            {review}
            """);

    public static final PromptTemplate PREVIOUS_REVIEW = new PromptTemplate(
            """
            Please note that previously you already have submitted the following code: 
            
            {code}
            
            And received the following review:
            
            {code_review}
            """
    );

    private final PromptTemplate USER_PROMPT_OPTIMIZER_TEMPLATE = new PromptTemplate("""
            Please, analyze the incoming source code and conduct very thorough code review.
            
            If you found any performance/architectural/concurrency etc problems - please, outline them.
            Be very picky.
            
            Here is the source code:
            
            {content}
            """);

    private final PromptTemplate SYSTEM_PROMPT_EVALUATOR = new PromptTemplate("""
            You are the professional, qualified Senior Software Engineer.
            
            You're writing code that is going to be later reviewed by your peer. 
            The review will be added
            """);

    private final PromptTemplate SYSTEM_PROMPT_OPTIMIZER = new PromptTemplate("""
            You are the professional, qualified Senior Software Engineer.
            
            Your job is to review the source code generated by your peer and conduct honest but thorough review.
            
            Your job is to provide the feedback, and each time the feedback is provided your MUST end your response
            with the line:
            
            Final Verdict: <VERDICT>
            
            Where the VERDICT is either: APPROVE or DECLINE
            """);

    // Image prompts end

    /**
     * Maximum amount of epochs that is allowed
     */
    private static final Integer MAX_EPOCH_COUNT = 10;

    private final ChatClient mistralEvaluator;
    private final ChatClient llamaOptimizer;

    public EvaluatorOptimizerService(ChatClient mistralEvaluator, ChatClient llamaOptimizer) {
        this.mistralEvaluator = mistralEvaluator;
        this.llamaOptimizer = llamaOptimizer;
    }

    public String evaluateOptimize(String prompt) {

        int epoch = 1;

        // TODO:
        //  ideally, in order to raise the quality, we need to support a context window here
        //  via ChatMemory and corresponding ChatMemoryRepository.
        String review = "";

        do {
            String generatedCode = evaluate(prompt, review);

            log.info("Epoch {}. Prompt: {} Solution : {}", epoch, prompt, generatedCode);

            String optimizerResponse = llamaOptimizer.prompt(
                    Prompt
                            .builder()
                            .messages(
                                    new SystemMessage(SYSTEM_PROMPT_OPTIMIZER.render()),
                                    new UserMessage(USER_PROMPT_OPTIMIZER_TEMPLATE.render(Map.of("content", prompt)))
                            )
                            .build()
            ).call().content();

            List<String> tutorResponse = optimizerResponse.lines().toList();

            if (containsApprove(tutorResponse) || epoch > MAX_EPOCH_COUNT) {
                return generatedCode;
            } else {
                review = PREVIOUS_REVIEW.render(Map.of("code", generatedCode, "code_review", optimizerResponse));
                epoch++;
            }
        } while (true);
    }

    private static boolean containsApprove(List<String> tutorResponse) {
        return tutorResponse
                .get(tutorResponse.size() - 1)
                .toLowerCase()
                .contains("Final Verdict: APPROVE".toLowerCase());
    }

    private String evaluate(String prompt, String review) {
        return mistralEvaluator.prompt(
                Prompt
                        .builder()
                        .messages(
                                new SystemMessage(SYSTEM_PROMPT_EVALUATOR.render()),
                                new UserMessage(USER_PROMPT_EVALUATOR_TEMPLATE.render(Map.of("content", prompt, "review", review)))
                        )
                        .build()
        ).call().content();
    }
}
